### PR TITLE
Fixes #219:  Make sidebar display on all pages in the /docs folder

### LINKED ISSUE #219: Make sidebar display on all pages in the /docs folder
_writeup in progress_...

Doesn't seem to be an option built into Docusaurus.

The sidebar currently will only display if a document is specifically listed in **sidebar.js**

We can't list every single document in **sidebar.js** it would be big problem for user navigation.

---

## ChatGPT explanation:

Install the remark and remark-frontmatter plugins:

`npm install remark remark-frontmatter --save-dev`

Create a script that will automatically add the displayedSidebar: docSidebar option to the front matter of all .md files in the /docs folder. Save this script as add-displayed-sidebar.js:

```
const fs = require("fs");
const path = require("path");
const remark = require("remark");
const frontmatter = require("remark-frontmatter");
const yaml = require("js-yaml");

function addDisplayedSidebarToDocs() {
  const docsFolder = path.join(__dirname, "docs");

  fs.readdirSync(docsFolder).forEach((file) => {
    const filePath = path.join(docsFolder, file);
    const content = fs.readFileSync(filePath, "utf-8");

    remark()
      .use(frontmatter, ["yaml"])
      .process(content, (err, file) => {
        if (err) {
          console.error("Error processing file:", filePath);
          return;
        }

        const fm = yaml.safeLoad(file);
        if (!fm.displayedSidebar) {
          fm.displayedSidebar = "docSidebar";
        }

        const updatedContent = `---
${yaml.safeDump(fm)}---
${file.contents}`;

        fs.writeFileSync(filePath, updatedContent, "utf-8");
      });
  });
}

addDisplayedSidebarToDocs();
```

Run the script to automatically add displayedSidebar: docSidebar to all .md files in the /docs folder:

`npm run add-displayed-sidebar`

---

In order to do this in build process when running `npm run build`, we need to make a custom plugin:

1. Create a new folder named custom-plugins in your Docusaurus project root directory.
2. Inside the custom-plugins folder, create a new file named auto-set-displayed-sidebar.js.
3. Add the following code to auto-set-displayed-sidebar.js:

```
const fs = require('fs');
const path = require('path');
const { promisify } = require('util');
const { parse } = require('yaml');

const readdirAsync = promisify(fs.readdir);
const readFileAsync = promisify(fs.readFile);
const writeFileAsync = promisify(fs.writeFile);

async function autoSetDisplayedSidebar() {
  const docsFolderPath = path.resolve(__dirname, '../docs');

  const files = await readdirAsync(docsFolderPath);
  for (const file of files) {
    const filePath = path.resolve(docsFolderPath, file);
    const fileContents = await readFileAsync(filePath, 'utf-8');
    const frontmatterStart = fileContents.indexOf('---') + 3;
    const frontmatterEnd = fileContents.indexOf('---', frontmatterStart);

    if (frontmatterStart !== -1 && frontmatterEnd !== -1) {
      const frontmatterContent = fileContents.slice(frontmatterStart, frontmatterEnd);
      const frontmatter = parse(frontmatterContent);

      if (!frontmatter.displayedSidebar) {
        frontmatter.displayedSidebar = 'docSidebar';
        const newFrontmatterContent = `---\n${Object.entries(frontmatter).map(([key, value]) => `${key}: ${JSON.stringify(value)}`).join('\n')}\n---`;
        const newFileContents = fileContents.slice(0, frontmatterStart) + newFrontmatterContent + fileContents.slice(frontmatterEnd);
        await writeFileAsync(filePath, newFileContents, 'utf-8');
      }
    }
  }
}

module.exports = function (context) {
  return {
    name: 'auto-set-displayed-sidebar',
    async loadContent() {
      await autoSetDisplayedSidebar();
      return null;
    },
  };
};

```

### PR DESCRIPTION
**Pull request by Sugamgoel28**
# Pull Request for #219: Added auto-set-displayed-sidebar script

## Description:
Previously, only `.md` files with the `displayed_sidebar` attribute were rendered with a sidebar. However, manually adding this attribute to each `.md` file was impractical. To address this issue, a custom plugin named "auto-set-displayed-sidebar" has been developed. This plugin automatically adds the `displayed_sidebar` attribute to `.md` files where it is missing.

## Changes Made:
- Created a custom plugin folder and added the script `auto-set-displayed-sidebar.js`.
- Configured the custom plugin in the `docusaurus.config.js` file.
- Executed the script to add the missing `displayed_sidebar` property and committed the updated `.md` files.

## Related Issues:
This pull request resolves issue #219.

### Before Fix:
Before Fix

### After Fix:
After Fix

---
This pull request addresses the need for a more automated approach to ensure consistency in rendering `.md` files with the sidebar. Your feedback and suggestions for further improvements are welcome. Thank you!

### CODE REVIEW

**Comment by futuresoup** [comment]
@Sugamgoel28 thank you! - just one question: can this be manually turned of on an individual .md page's front matter?

For example - something like this:

```
---
displayed_sidebar: off
---
```

Probably not a huge need, but there may be situations where pages should be rendered without a sidebar and it could be a nice option to have.

If you don't think it's worth doing, then I'll merge this one.

**Comment by Sugamgoel28** [comment]
> @Sugamgoel28 thank you! - just one question: can this be manually overridden to turn of on the sidebar on an individual .md page's front matter?
> 
> For example - this syntax in the .md front matter at the top of the doc will turn off the sidebar
> 
> ```
> ---
> displayed_sidebar: null
> ---
> ```
> 
> Probably not a huge need, but there may be situations where pages should be rendered without a sidebar and it could be a nice option to have.
> 
> If you don't think it's worth doing, then I'll merge this one.

Hi again! I attempted to overwrite it by setting the attribute to null.

However, upon running `npm run build`, the custom plugin script is triggered, scanning through all the .md files and adding the `displayed_sidebar` attribute to those where it is absent. Consequently, manual overwriting proved ineffective.

I'd probably need to modify the script in order to cover that edge case. Would you like to me brainstorm a solution for it?

**Comment by Sugamgoel28** [comment]
I've figured it out, this could be done easily by just adding one conditional in the script. Should I update and commit this?

```ts
if(frontmatter.displayed_sidebar === null){
        continue;
      }
```

**Comment by futuresoup** [comment]
@Sugamgoel28 sounds perfect, yes please add it thank you and congrats on making your first major contribution :D

**Pull request closed without merging**
